---
title: "SCLC Analysis"
author: "Andrew Willems & Tian Hong"
date: "2023-04-05"
output: html_document
---

```{r setup, include=FALSE}
# This sets the global chunk options for knitr to display the R code.
knitr::opts_chunk$set(echo = TRUE)

# This sets the root directory for knitr to the project directory.
knitr::opts_knit$set(root.dir = "~/Documents/Work/Phd_program/hong_lab/Projects/sclc/")
```

## SCLC Analysis

```{r load needed packages}
# Load necessary packages using the pacman package
# data.table: for efficient data manipulation
# devtools: for developing R packages
# ggplot2: for data visualization
# glmnet: for fitting generalized linear models via penalized maximum likelihood
# hoardr: for caching data to disk
# Matrix: for sparse matrix operations
# monocle3: for single-cell analysis and visualization
# phateR: for visualizing high-dimensional data
# reticulate: for running Python code in R
# retry: for allowing us to repeatedly restart code due to timeouts
# Rmagic: for running R code in Jupyter notebooks
# styler: for consistent code formatting
# survminer: for survival analysis and visualization
# tidyverse: for data manipulation and visualization
# viridis: for creating color palettes for data visualization

pacman::p_load(
  cowplot, data.table, devtools, ggplot2, glmnet, hoardeR, igraph, Matrix, monocle3, parallel, phateR,
  reticulate, retry, Rmagic, styler, survival, survminer, svglite, switchde, tidyverse, viridis
)
```

```{r miniconda setup for MAGIC}
# Loading conda environment 'r-reticulate' for MAGIC package
use_condaenv("/Users/andrewwillems/Library/r-miniconda-arm64/envs/r-reticulate")
```


```{r sourcing needed functions}
# This code sources several R scripts that contain functions used for analyzing miRNA expression data in lung cancer.
# The 'back_elim.R' script contains a function for performing backwards variable selection on the Cox model to identify the most significant miRNAs associated with survival.
# The 'cox_model.R' script contains a function for performing a Cox proportional hazards model on the data.
# The 'km_plotter.R' script contains a function for creating a Kaplan-Meier plot to visualize survival data.
# The 'lung_mirna_calculator.R' script contains functions for preprocessing and normalizing the miRNA expression data.
# The 'risk_score_calculator.R' script contains a function for calculating a risk score for each patient based on the results of the Cox model.
# This code also sources 'cell_dataset_builder.R', which contains functions for building a dataset from processed scRNA-seq expression data.

invisible(lapply(list.files("Code", pattern = "\\.R$", full.names = TRUE), source))
```


```{r reading data}
# Load gene expression data from a file and select relevant columns
scl_df <- read.csv(
  file = "Data/sclc_ucologne_2015/data_mrna_seq_rpkm.txt",
  sep = "\t"
)
scl_df <- subset(scl_df,
  select = c(Hugo_Symbol, sclc_ucologne_2015_S00022:sclc_ucologne_2015_S02397)
)

# Clean up column names by removing prefix
colnames(scl_df) <- sub("^sclc_ucologne_2015_S", "", colnames(scl_df))

# Load clinical data for patients and clean up column names and values
scl_patient <- read.csv(
  file = "Data/sclc_ucologne_2015/data_clinical_patient.txt",
  sep = "\t"
)

scl_patient <- scl_patient %>%
  slice(5:121) %>%
  rename(
    Patient.ID = X.Patient.Identifier, Overall.Survival.Status = Overall.Survival.Status,
    Overall.Survival.Months. = Overall.Survival..Months., Smoker = Smoker
  ) %>%
  select(Patient.ID, Sex, Overall.Survival.Status, Overall.Survival.Months., Smoker, Chemotherapy, Neoadjuvant.Chemotherapy, N.Stage, M.Stage, UICC.Tumor.Stage) %>%
  filter(Smoker != "Never") %>%
  filter(Smoker != "") %>%
  mutate(
    Smoker = as.factor(Smoker),
    Smoker = if_else(Smoker == "Current", true = 1, false = 0)
  ) %>%
  mutate(Overall.Survival.Status = ifelse(Overall.Survival.Status == "1:DECEASED", 1, 0)) %>%
  rename(
    vital.status = Overall.Survival.Status,
    time = Overall.Survival.Months.
  ) %>%
  mutate(Patient.ID = gsub(
    x = Patient.ID,
    pattern = "sclc_ucologne_2015_S",
    replacement = ""
  )) %>%
  mutate(vital.status_new = as.numeric(vital.status)) %>%
  mutate(time_new = as.numeric(time)) %>%
  select(-vital.status, -time) %>%
  rename(
    vital.status = vital.status_new,
    time = time_new
  ) %>%
  mutate(time = time * 30) %>%
  filter(time != 0) %>%
  rename_all(tolower)

# Extract the list of gene symbols
scl_genes <- scl_df$Hugo_Symbol

# Find the list of patients that have data for both gene expression and clinical data
common_patients <- intersect(scl_patient$patient.id, colnames(scl_df))

# Select only the common columns from gene expression data and transpose it
# so that each row corresponds to a patient
scl_common <- scl_df %>%
  select(all_of(common_patients)) %>%
  t() %>%
  as.data.frame()

# Assign the gene symbols as column names
colnames(scl_common) <- scl_genes

# Remove duplicated columns and add patient ID as a column
scl_common <- scl_common %>%
  select(-which(duplicated(names(.)))) %>%
  rownames_to_column(var = "patient.id")

# Join the gene expression data with the clinical data for each patient
scl_common <- left_join(scl_common, scl_patient[, c(
  "sex", "smoker",
  "vital.status", "time",
  "patient.id", "n.stage", "m.stage", "uicc.tumor.stage",
  "chemotherapy", "neoadjuvant.chemotherapy"
)],
by = "patient.id"
) %>%
  rename_all(tolower) %>%
  select(
    patient.id, sex, smoker, vital.status, time, n.stage, m.stage,
    uicc.tumor.stage, chemotherapy, neoadjuvant.chemotherapy, everything()
  )

# Removing intermediate files to keep the environment clean
rm(scl_df, scl_patient, scl_genes, common_patients)
```


```{r single-cell data loading}
# Read in the gene expression data and filter out columns that start with "SCLC_P1" or "SCLC_P14"
sc_df <- fread("Data/OMIX002441-01.csv")
sc_df <- sc_df %>%
  select(-matches("^(SCLC_P1|SCLC_P14)")) %>%
  t() # transpose the data frame to have cells as rows

# Set column names to the first row of the data frame
colnames(sc_df) <- sc_df["V1", ]
sc_df <- sc_df[-1, ] # remove first row, which is now redundant
sc_df <- as.data.frame(sc_df)

# Read in the metadata and filter for tumor samples only
meta_data <- fread("Data/OMIX002441-02.csv")
meta_data <- meta_data %>%
  filter(NT == "tumor")

# Set row names to the first column, which contains the cell IDs
colnames(meta_data)[1] <- "id"

# Join the two dataframes on the "id" column
sc_df$id <- rownames(sc_df)
sc_df <- inner_join(sc_df, meta_data, by = "id")
rownames(sc_df) <- sc_df$id
sc_df <- sc_df %>% select(-id, -patient, -NT, -tissue, -cell_type, -nCount_RNA, -nFeature_RNA, -Pre_Map_Reads, -Aligned_Reads, -MappingRate)

# Keep only genes that are expressed in at least 10 cells
keep_cols <- colSums(sc_df > 0) > 10
sc_df <- sc_df[, keep_cols]

sc_rownames <- rownames(sc_df)

# Convert the data frame to integers
sc_df <- apply(sc_df, c(1, 2), as.integer) %>%
  as.data.frame()

rownames(sc_df) <- sc_rownames

# Plot the distribution of library sizes
p1 <- ggplot() +
  geom_histogram(aes(x = rowSums(sc_df)), bins = 50) +
  geom_vline(xintercept = 1000, color = "red") +
  theme(
    panel.background = element_blank(),
    axis.title = element_text(size = 22, face = "bold"),
    axis.text = element_text(size = 20),
    plot.title = element_text(size = 24, face = "bold", hjust = 0.5),
    axis.ticks = element_line(linewidth = 1.25),
    axis.ticks.length = unit(0.2, units = "cm"),
    axis.line = element_line(color = "black", linewidth = 1.25),
    plot.subtitle = element_text(hjust = 0.5, size = 22)
  ) +
  ggtitle("Distribution of Library Sizes in scRNA-seq", subtitle = "Distribution of library sizes after keeping genes that have positive (> 0) expression in at least 10 cells") +
  xlab("Library Size") +
  ylab("Count") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0))

ggsave(plot = p1, width = 20, height = 20, units = "in", dpi = 600, device = "png", filename = "sc_library_distribution_sizes.png", path = "Outputs/")
ggsave(plot = p1, width = 20, height = 20, units = "in", dpi = 600, device = "svg", filename = "sc_library_distribution_sizes.svg", path = "Outputs/")

# Keep only cells with a library size between 1000 and 15000
keep_rows <- rowSums(sc_df) > 1000 & rowSums(sc_df) < 15000
sc_df <- sc_df[keep_rows, ]

# Normalize the library size and take the square root of the expression values
sc_df <- library.size.normalize(sc_df)
sc_df <- sqrt(sc_df)

# Removing intermediate files to keep the environment tidy
rm(keep_cols, keep_rows, sc_rownames, p1)
```

```{r single-cell denoising}
# Convert the sc_df dataframe to a matrix
sc_df_mat <- as.matrix(sc_df)

# Apply the MAGIC (Model-based Analysis of Genome-wide CRISPR/Cas9 Knockout) algorithm to denoise the scRNA-seq data.
# The 'genes' parameter specifies the set of genes to use for MAGIC imputation. Here, 'all_genes' is used to include all genes in the analysis.
# The 'seed' parameter specifies a random seed for reproducibility.
# The 'n.jobs' parameter specifies the number of cores to use for parallelization. Setting it to -1 indicates that all available cores should be used.
sc_denoised <- magic(sc_df_mat, genes = "all_genes", seed = 123, n.jobs = -1)

saveRDS(sc_denoised, "Outputs/denoised_sc_data.rds")

rm(sc_df_mat)
```


```{r generating pseudotime from single-cell data}
sc_denoised$result <- sc_denoised$result %>%
  t()

meta_data <- meta_data %>%
  filter(id %in% colnames(sc_denoised$result)) %>%
  column_to_rownames(var = "id")

cds_cell_meta <- meta_data
cds_gene_meta <- data.frame(gene_short_name = rownames(sc_denoised$result))
rownames(cds_gene_meta) <- cds_gene_meta$gene_short_name

emt_genes <- read.csv("Data/emt_genes_tian.txt", sep = "\t")

# Getting common genes between EMT list and our list
common_emt_genes <- intersect(cds_gene_meta$gene_short_name, emt_genes$Gene)
common_emt_genes <- data.frame(gene_short_name = common_emt_genes)
rownames(common_emt_genes) <- common_emt_genes$gene_short_name

cds_output <- cell_dataset_builder(
  gene_expression = "TUBA1A",
  cell_data = sc_denoised$result,
  gene_meta = cds_gene_meta,
  cell_meta = cds_cell_meta,
  pt_root = "Y_7",
  gene_title = "TUBA1A",
  pt_title = "TUBA1A",
  point_size = 2.5,
  norm_flag = "none",
  use_ordering_funct = FALSE,
  cds_filename = "Outputs/cds.rds",
  plot_file = "Outputs/emt_gene_expression.png",
  pt_file = "Outputs/pt_expression.png",
  pt_data_filename = "Outputs/TUBA1A_pseudotime_data.csv"
)

# Bringing the cell expression and pseudotime graphs together into a single plot
combo_plot <- ggarrange(cds_output$Cell_Progression_Graph, cds_output$PT_Graph, ncol = 2, nrow = 1, align = "h", labels = c("A.", "B."), legend = "bottom", font.label = c(size = 18))
combo_plot <- combo_plot + ggtitle("SDE Pseudotime Ordering") +
  theme(
    plot.title = element_text(size = 22, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, size = 9)
  )

# add a caption using ggdraw
caption_text <- "Figure S1: Panel A shows the gene expression levels of TUBA1A, which is a marker for mesenchymal cells during epithelial-mesenchymal transition (EMT). This gene's expression levels were used as the basis for calculating pseudotime in our single-cell RNA sequencing (scRNA-seq) dataset.

Panel B shows the calculated pseudotime of the scRNA-seq dataset, based on the expression levels of TUBA1A in panel A. The annotations of 1 and 2 (seen in white circles) indicate the roots of the pseudotime calculations, where the pseudotime is equal to 0. As we move along the trajectory (represented by the solid black line), the pseudotime values increase, mirroring the expression pattern of TUBA1A. "
caption <- ggdraw() +
  draw_label(caption_text, fontface = "plain", size = 10, x = 0, hjust = 0)

# add the caption to the bottom of the plot
plots_with_caption <- plot_grid(combo_plot, caption, nrow = 2, align = "v", axis = "tblr")


ggsave(
  plot = combo_plot, device = "png", dpi = 600, width = 7, height = 5,
  units = "in", filename = "Outputs/sde_foundation_plot.png", bg = "white"
)

ggsave(
  plot = combo_plot, device = "svg", dpi = 600, width = 7, height = 5,
  units = "in", filename = "Outputs/sde_foundation_plot.svg", bg = "white"
)
```

```{r sde metric}
sde_genes <- switchde_calculator(sc_denoised$result,
  pseudo_time = cds_output$PT_Data
)

saveRDS(sde_genes, "Outputs/sde_genes.rds")

head(sde_genes)
```


```{r ideal gene number for sde metric}
gene_sizes <- seq(1, 20, 1)
cox_outputs <- list()
counter <- 1
for (gn in gene_sizes) {
  current_cox <- cox_model_fitter(my_seed = 1, my_alpha = 1, cox_predictors = sde_genes, cox_df = scl_common, gene_num = gn, n_folds = 10, calc_auc = FALSE, save_coefs = FALSE, verbose = FALSE, cat_preds = FALSE)
  cox_outputs[[counter]] <- current_cox
  cindex <- round(current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)], digits = 4)
  cindex_active_genes <- as.numeric(as.vector(current_cox$CV$nzero[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]))
  lambda <- current_cox$CV$lambda.min
  measure <- "Concordance-index"
  cindex_se <- round(as.numeric(current_cox$CV$cvsd[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]), digits = 4)
  cindex_index <- current_cox$CV$index["min", ]
  cindex_df <- as.data.frame(cbind(cindex, cindex_se, cindex_active_genes, lambda, measure, cindex_index))
  write.csv(cindex_df, paste0("Outputs/sde/glmnet_", gn, "_genes_glmnet_index_", cindex_index, "_lambda_", lambda, ".csv"))
  counter <- counter + 1
}


# Now seeing what the best c-index is
read_files <- function(folder_path, pattern) {
  # Get a list of all files in the folder that match the pattern
  file_list <- list.files(path = folder_path, pattern = pattern, full.names = TRUE)

  # Read in all CSV files and combine into a single dataframe
  data <- do.call(rbind, lapply(file_list, read.csv))

  return(data)
}

all_sde_cindices <- read_files(folder_path = "Outputs/sde/", pattern = "*.csv")
max_sde_cindex <- all_mad_cindices[which.max(all_sde_cindices$cindex), ] # 0.7221 with 7 active genes
```

```{r mad metric}
mad_genes <- mad_calculator(sc_denoised$result)
saveRDS(mad_genes, "Outputs/mad_genes.rds")
head(mad_genes)
```

```{r ideal gene size for mad}
gene_sizes <- seq(1, 20, 1)
cox_outputs <- list()
counter <- 1
for (gn in gene_sizes) {
  current_cox <- cox_model_fitter(my_seed = 1, my_alpha = 1, cox_predictors = mad_genes, cox_df = scl_common, gene_num = gn, n_folds = 10, calc_auc = FALSE, save_coefs = FALSE, verbose = FALSE, cat_preds = FALSE)
  cox_outputs[[counter]] <- current_cox
  cindex <- round(current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)], digits = 4)
  cindex_active_genes <- as.numeric(as.vector(current_cox$CV$nzero[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]))
  lambda <- current_cox$CV$lambda.min
  measure <- "Concordance-index"
  cindex_se <- round(as.numeric(current_cox$CV$cvsd[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]), digits = 4)
  cindex_index <- current_cox$CV$index["min", ]
  cindex_df <- as.data.frame(cbind(cindex, cindex_se, cindex_active_genes, lambda, measure, cindex_index))
  write.csv(cindex_df, paste0("Outputs/mad/glmnet_", gn, "_genes_glmnet_index_", cindex_index, "_lambda_", lambda, ".csv"))
  counter <- counter + 1
}


# Now seeing what the best c-index is
read_files <- function(folder_path, pattern) {
  # Get a list of all files in the folder that match the pattern
  file_list <- list.files(path = folder_path, pattern = pattern, full.names = TRUE)

  # Read in all CSV files and combine into a single dataframe
  data <- do.call(rbind, lapply(file_list, read.csv))

  return(data)
}

all_mad_cindices <- read_files(folder_path = "Outputs/mad/", pattern = "*.csv")
max_mad_cindex <- all_mad_cindices[which.max(all_mad_cindices$cindex), ] # 0.7718 with 13 active genes
all_mad_cindices_sub <- all_mad_cindices %>% filter(cindex_active_genes == 7 | cindex_active_genes == 8) # 0.7221 with 7 active genes
```


```{r mirna with small number of active genes cindex}
file_list <- list.files(path = "Outputs/mirna/rds", pattern = "*.rds", full.names = TRUE)
file_list <- file_list[!grepl("_mat_", file_list)]

gene_sizes <- seq(2, 8, 1)
cox_outputs <- list()
counter <- 1
for (f in file_list) {
  print(f)
  for (gn in gene_sizes) {
    current_mirna_met <- readRDS(paste0(f))
    current_cox <- cox_model_fitter(my_seed = 1, my_alpha = 1, cox_predictors = current_mirna_met, cox_df = scl_common, gene_num = gn, n_folds = 10, calc_auc = FALSE, save_coefs = FALSE, verbose = FALSE, cat_preds = FALSE)
    cox_outputs[[counter]] <- current_cox
    mirna_genes <- str_extract(f, "(?<=mirna_genes_)\\d+")
    mirnas <- str_extract(f, "(?<=mirnas_)\\d+")
    cindex <- round(current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)], digits = 4)
    cindex_active_genes <- as.numeric(as.vector(current_cox$CV$nzero[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]))
    lambda <- current_cox$CV$lambda.min
    measure <- "Concordance-index"
    cindex_se <- round(as.numeric(current_cox$CV$cvsd[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]), digits = 4)
    cindex_index <- current_cox$CV$index["min", ]
    cindex_df <- as.data.frame(cbind(cindex, cindex_se, cindex_active_genes, lambda, measure, cindex_index))
    write.csv(cindex_df, paste0("Outputs/mirna/glmnet_", gn, "_genes_glmnet_index_", cindex_index, "_lambda_", lambda, "_mirnas_", mirnas, "_targets_", mirna_genes, ".csv"))
    counter <- counter + 1
  }
}
```

```{r loading in all mirna outputs for small size and finding performance}
# Now seeing what the best c-index is
read_files <- function(folder_path, pattern) {
  # Get a list of all files in the folder that match the pattern
  file_list <- list.files(path = folder_path, pattern = pattern, full.names = TRUE)

  # Read in all CSV files and combine into a single dataframe
  data <- do.call(rbind, lapply(file_list, read.csv))

  return(data)
}

all_mirna_cindices <- read_files(folder_path = "Outputs/mirna/glmnet/", pattern = "*.csv")
max_mirna_cindex <- all_mirna_cindices[which.max(all_mirna_cindices$cindex), ] #  0.756 with 5 active genes
```

```{r barplot of the 3 individual metrics}
all_individual_met_df <- bind_rows(max_mirna_cindex, max_sde_cindex, all_mad_cindices_sub[1, ])
all_individual_met_df <- all_individual_met_df %>%
  mutate(metric = c("mirna", "sde", "mad"))
```

```{r generate a cox model with just the cancer staging to see performance}
scl_patient <- read.csv(
  file = "Data/sclc_ucologne_2015/data_clinical_patient.txt",
  sep = "\t"
)

scl_patient <- scl_patient %>%
  slice(5:121) %>%
  rename(
    Patient.ID = X.Patient.Identifier, Overall.Survival.Status = Overall.Survival.Status,
    Overall.Survival.Months. = Overall.Survival..Months., Smoker = Smoker
  ) %>%
  select(Patient.ID, Sex, Overall.Survival.Status, Overall.Survival.Months., Smoker, Sex, Ethnicity.Category, N.Stage, M.Stage, UICC.Tumor.Stage, Chemotherapy, Neoadjuvant.Chemotherapy) %>%
  filter(Smoker != "Never") %>%
  filter(Smoker != "") %>%
  mutate(
    Smoker = as.factor(Smoker),
    Smoker = if_else(Smoker == "Current", true = 1, false = 0)
  ) %>%
  mutate(Overall.Survival.Status = ifelse(Overall.Survival.Status == "1:DECEASED", 1, 0)) %>%
  rename(
    vital.status = Overall.Survival.Status,
    time = Overall.Survival.Months.
  ) %>%
  mutate(Patient.ID = gsub(
    x = Patient.ID,
    pattern = "sclc_ucologne_2015_S",
    replacement = ""
  )) %>%
  mutate(vital.status_new = as.numeric(vital.status)) %>%
  mutate(time_new = as.numeric(time)) %>%
  select(-vital.status, -time) %>%
  rename(
    vital.status = vital.status_new,
    time = time_new
  ) %>%
  mutate(time = time * 30) %>%
  filter(time != 0) %>%
  rename_all(tolower)

scl_clinical_only <- scl_patient %>%
  mutate(n.stage = ifelse(n.stage == "", NA, n.stage)) %>%
  mutate(m.stage = ifelse(m.stage == "", NA, m.stage)) %>%
  filter(!is.na(ethnicity.category) & !is.na(n.stage) & !is.na(m.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "Ia", 1, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "I", 1, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "Ib", 1, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "IB", 1, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "IIIa", 3, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "IV", 4, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "iib", 2, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "iia", 2, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "iiia", 3, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "iiib", 3, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "IIIa", 3, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "IIIb", 3, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "IIa", 2, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "IIb", 2, uicc.tumor.stage)) %>%
  mutate(uicc.tumor.stage = ifelse(uicc.tumor.stage == "II", 2, uicc.tumor.stage)) %>%
  mutate(n.stage = ifelse(n.stage == "1a", 1, n.stage)) %>%
  mutate(n.stage = ifelse(n.stage == "1b", 1, n.stage)) %>%
  mutate(n.stage = ifelse(n.stage == "X", "x", n.stage)) %>%
  mutate(m.stage = ifelse(m.stage == "1a", 1, m.stage)) %>%
  mutate(m.stage = ifelse(m.stage == "1b", 1, m.stage))

surv_y <- Surv(time = scl_clinical_only$time, event = scl_clinical_only$vital.status, type = "right")
clinical_cox_only <- coxph(data = scl_clinical_only, formula = surv_y ~ n.stage + m.stage + uicc.tumor.stage)
summary_clinical <- summary(clinical_cox_only)
clinical_staging_only_cindex <- round(as.numeric(as.vector(summary_clinical$concordance["C"])), digits = 4) # 0.6205 with 9 active predictors
clinical_staging_only_cindex_se <- round(as.numeric(as.vector(summary_clinical$concordance["se(C)"])), digits = 4)

clinical_staging_only_df <- data.frame(X = 1, cindex = clinical_staging_only_cindex, cindex_se = clinical_staging_only_cindex_se, cindex_active_genes = 9, lambda = NA, measure = "Concordance-index", cindex_index = NA, metric = "clinical_staging")
# Adding staging c-index to df of other individual metrics
all_individual_met_df <- bind_rows(all_individual_met_df, clinical_staging_only_df)
```


```{r random gene selection}
scl_common <- scl_common %>%
  select(
    -patient.id, -sex, -smoker, -vital.status, -time, -n.stage, -m.stage,
    -uicc.tumor.stage, -chemotherapy, -neoadjuvant.chemotherapy
  )

# Function to randomly sample genes from the dataset
sample_genes <- function(df, n_genes, n_samples = 1000) {
  gene_names <- colnames(df)
  n_genes <- min(n_genes, length(gene_names))
  samples <- lapply(1:n_samples, function(x) {
    df %>%
      select(sample(gene_names, n_genes, replace = FALSE)) %>%
      rename_all(tolower)
  })
  return(samples)
}


set.seed(123)
sampled_genes <- sample_genes(df = scl_common, n_genes = 7, n_samples = 1000)

# Re-loading the scl file so that we can include the meta data
scl_patient <- read.csv(
  file = "Data/sclc_ucologne_2015/data_clinical_patient.txt",
  sep = "\t"
)

scl_patient <- scl_patient %>%
  slice(5:121) %>%
  rename(
    Patient.ID = X.Patient.Identifier, Overall.Survival.Status = Overall.Survival.Status,
    Overall.Survival.Months. = Overall.Survival..Months., Smoker = Smoker
  ) %>%
  select(Patient.ID, Sex, Overall.Survival.Status, Overall.Survival.Months., Smoker, Sex) %>%
  filter(Smoker != "Never") %>%
  filter(Smoker != "") %>%
  mutate(
    Smoker = as.factor(Smoker),
    Smoker = if_else(Smoker == "Current", true = 1, false = 0)
  ) %>%
  mutate(Overall.Survival.Status = ifelse(Overall.Survival.Status == "1:DECEASED", 1, 0)) %>%
  rename(
    vital.status = Overall.Survival.Status,
    time = Overall.Survival.Months.
  ) %>%
  mutate(Patient.ID = gsub(
    x = Patient.ID,
    pattern = "sclc_ucologne_2015_S",
    replacement = ""
  )) %>%
  mutate(vital.status_new = as.numeric(vital.status)) %>%
  mutate(time_new = as.numeric(time)) %>%
  select(-vital.status, -time) %>%
  rename(
    vital.status = vital.status_new,
    time = time_new
  ) %>%
  mutate(time = time * 30) %>%
  filter(time != 0) %>%
  rename_all(tolower)


# Extract the list of gene symbols
scl_genes <- scl_df$Hugo_Symbol

# Find the list of patients that have data for both gene expression and clinical data
common_patients <- intersect(scl_patient$patient.id, colnames(scl_df))

# Select only the common columns from gene expression data and transpose it
# so that each row corresponds to a patient
scl_common <- scl_df %>%
  select(all_of(common_patients)) %>%
  t() %>%
  as.data.frame()

# Assign the gene symbols as column names
colnames(scl_common) <- scl_genes

# Remove duplicated columns and add patient ID as a column
scl_common <- scl_common %>%
  select(-which(duplicated(names(.)))) %>%
  rownames_to_column(var = "patient.id")

# Join the gene expression data with the clinical data for each patient
scl_common <- left_join(scl_common, scl_patient[, c(
  "vital.status", "time",
  "patient.id"
)],
by = "patient.id"
) %>%
  rename_all(tolower) %>%
  select(
    patient.id, vital.status, time, everything()
  )


counter <- 1
cox_outputs <- list()
for (g in sampled_genes) {
  current_genes <- g
  current_cox <- cox_model_fitter(my_seed = 1, my_alpha = 1, cox_predictors = current_genes, cox_df = scl_common, gene_num = 7, n_folds = 10, calc_auc = FALSE, save_coefs = FALSE, verbose = FALSE, cat_preds = FALSE)
  cox_outputs[[counter]] <- current_cox

  if (is.null(current_cox)) {
    next
  } else {
    cindex <- round(current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)], digits = 4)
    cindex_active_genes <- as.numeric(as.vector(current_cox$CV$nzero[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]))
    lambda <- current_cox$CV$lambda.min
    measure <- "Concordance-index"
    cindex_se <- round(as.numeric(current_cox$CV$cvsd[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]), digits = 4)
    cindex_index <- current_cox$CV$index["min", ]
    cindex_df <- as.data.frame(cbind(cindex, cindex_se, cindex_active_genes, lambda, measure, cindex_index))
    write.csv(cindex_df, paste0("Outputs/glmnet_cindices/random_genes/glmnet_7_genes_glmnet_index_", cindex_index, "_lambda_", lambda, ".csv"))
    counter <- counter + 1
  }
}


# Combining all files together
all_random_cindices <- read_files(folder_path = "Outputs/glmnet_cindices/random_genes/", pattern = "*.csv")
mean_random_cindices <- mean(all_random_cindices$cindex) # 0.606116
random_genes_only_df <- data.frame(X = 1, cindex = mean_random_cindices, cindex_se = NA, cindex_active_genes = NA, lambda = NA, measure = "Concordance-index", cindex_index = NA, metric = "random_genes")
# Adding staging c-index to df of other individual metrics
all_individual_met_df <- bind_rows(all_individual_met_df, random_genes_only_df)
```

```{r mirna}
# Load the data
mirna_data <- read.csv("Data/mirna_data/hmdd_3_2_all_data.txt", sep = "\t")

# Filter the data down to just miRNAs that are lung related and are
# classified as upregulated/increased
mirna_data <- mirna_data %>%
  filter(grepl("up", category)) %>%
  filter(disease %in% c(
    "Lung Disease [unspecific]", "Lung Fibrosis",
    "Lung Injury [unspecific]", "Lung Neoplasms"
  )) %>%
  select(mir)


# Now sending those miRNAs to TargetScan
mirna_num <- seq(100, 800, 100)
mirna_target_num <- seq(2, 8, 1)
# mirna_target_num <- seq(100, 5000, 200)
# mirna_target_num <- seq(1, 100, 1)
for (m in mirna_num[1:4]) {
  for (t in mirna_target_num[1:7]) {
    mirna_genes <- mirna_calculator(ts_org = "Human", ts_version = "8.0", max_mir_targets = t, cancer_up = TRUE, cancer_type1 = "lung cancer", print_ts_targets = FALSE, status = "up", max_mirnas = m, mirna_genes_mat_name = paste0("Outputs/mirna/mirna_genes_mat_", m, "_mirnas_", t, "_targets_up.csv"), mirna_ranking_name = paste0("Outputs/mirna/mirna_genes_", m, "_mirnas_", t, "_targets_up_.csv"), mirna_ranking_name_rds = paste0("Outputs/mirna/mirna_genes_", m, "_mirnas_", t, "_targets_up_.rds"), mirna_genes_mat_name_rds = paste0("Outputs/mirna/mirna_genes_mat_", m, "_mirnas_", t, "_targets_up.rds"))
  }
}
```




```{r cox model for different miRNA data from increased miRNA}
file_list <- list.files(path = "Outputs/increased_mirna_targets", pattern = "*.rds", full.names = TRUE)
gene_sizes <- seq(2, 100, 1)
cox_outputs <- list()
counter <- 1
for (f in file_list) {
  for (gn in gene_sizes) {
    current_mirna_met <- readRDS(paste0(f))
    current_cox <- cox_model_fitter(my_seed = 1, my_alpha = 1, cox_predictors = current_mirna_met, cox_df = scl_common, gene_num = gn, n_folds = 10, calc_auc = FALSE, save_coefs = FALSE, verbose = FALSE, cat_preds = FALSE)
    cox_outputs[[counter]] <- current_cox
    mirna_genes <- str_extract(f, "(?<=mirna_genes_)\\d+")
    mirnas <- str_extract(f, "(?<=mirnas_)\\d+")
    cindex <- round(current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)], digits = 4)
    cindex_active_genes <- as.numeric(as.vector(current_cox$CV$nzero[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]))
    lambda <- current_cox$CV$lambda.min
    measure <- "Concordance-index"
    cindex_se <- round(as.numeric(current_cox$CV$cvsd[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]), digits = 4)
    cindex_index <- current_cox$CV$index["min", ]
    cindex_df <- as.data.frame(cbind(cindex, cindex_se, cindex_active_genes, lambda, measure, cindex_index))
    write.csv(cindex_df, paste0("Outputs/glmnet_cindices/100_targets/glmnet_", gn, "_genes_glmnet_index_", cindex_index, "_lambda_", lambda, "_mirnas_", mirnas, "_targets_", mirna_genes, ".csv"))
    counter <- counter + 1
  }
}
```


```{r}
# Function to read and combine many files
function(folder_path, pattern) {
  # Get a list of all files in the folder that match the pattern
  file_list <- list.files(path = folder_path, pattern = pattern, full.names = TRUE)

  # Read in all CSV files and combine into a single dataframe
  data <- do.call(rbind, lapply(file_list, read.csv))

  return(data)
}

all_mirna_glmnet <- read_files(folder_path = "Outputs/glmnet_cindices/100_targets/", pattern = "*.csv")
```



```{r larger number of targets for up regulated miRNA}
file_list <- list.files(path = "Outputs/increased_mirna_targets/metrics/5000_targets", pattern = "5000_targets.rds", full.names = TRUE)
gene_sizes <- seq(1, 5000, 200)
cox_outputs <- list()
counter <- 1
for (f in file_list) {
  for (gn in gene_sizes) {
    current_mirna_met <- readRDS(paste0(f))
    current_cox <- cox_model_fitter(my_seed = 1, my_alpha = 1, cox_predictors = current_mirna_met, cox_df = scl_common, gene_num = gn, n_folds = 10, calc_auc = FALSE, save_coefs = FALSE, verbose = FALSE, cat_preds = FALSE)
    cox_outputs[[counter]] <- current_cox
    mirna_genes <- str_extract(f, "(?<=mirna_genes_)\\d+")
    mirnas <- str_extract(f, "(?<=mirnas_)\\d+")
    cindex <- round(current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)], digits = 4)
    cindex_active_genes <- as.numeric(as.vector(current_cox$CV$nzero[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]))
    lambda <- current_cox$CV$lambda.min
    measure <- "Concordance-index"
    cindex_se <- round(as.numeric(current_cox$CV$cvsd[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]), digits = 4)
    cindex_index <- current_cox$CV$index["min", ]
    cindex_df <- as.data.frame(cbind(cindex, cindex_se, cindex_active_genes, lambda, measure, cindex_index))
    write.csv(cindex_df, paste0("Outputs/glmnet_cindices/5000_targets/glmnet_", gn, "_genes_glmnet_index_", cindex_index, "_lambda_", lambda, "_mirnas_", mirnas, "_targets_", mirna_genes, ".csv"))
    counter <- counter + 1
  }
}
```

```{r looking to see what kind of performance we have}
all_cindices <- read_files(folder_path = "Outputs/glmnet_cindices/5000_targets/", pattern = "*.csv")
```



```{r cox model for different miRNA data from decreased miRNA}
file_list <- list.files(path = "Outputs/decreased_mirna_targets/metrics/", pattern = "*.rds", full.names = TRUE)
gene_sizes <- seq(1, 10, 1)
cox_outputs <- list()
counter <- 1
for (f in file_list) {
  for (gn in gene_sizes) {
    current_mirna_met <- readRDS(paste0(f))
    current_cox <- cox_model_fitter(my_seed = 1, my_alpha = 1, cox_predictors = current_mirna_met, cox_df = scl_common, gene_num = gn, n_folds = 10, calc_auc = FALSE, save_coefs = FALSE, verbose = FALSE, cat_preds = FALSE)
    cox_outputs[[counter]] <- current_cox
    counter <- counter + 1
  }
}

cox_outputs <- cox_outputs[!sapply(cox_outputs, is.null)]
cindices <- c()
num_of_active_genes <- c()
for (c in 1:length(cox_outputs)) {
  current_cox <- cox_outputs[[c]]
  cindices <- c(cindices, current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)])
  num_of_active_genes <- c(num_of_active_genes, length(current_cox$`Active Genes`))
}

df <- as.data.frame(cbind(cindices, num_of_active_genes))
write.csv(df, "Outputs/decreased_mirna_targets/cindex_performance.csv")
```

```{r check how SDE performs across gene size}
# gene_sizes <- seq(1, 4000, 20)
gene_sizes <- seq(1, 20, 1)

for (gs in gene_sizes) {
  current_cox <- cox_model_fitter(
    my_seed = 1,
    my_alpha = 1,
    cox_predictors = mad_genes,
    cox_df = scl_common,
    gene_num = gs,
    save_coefs = FALSE,
    tumor_stage = FALSE,
    tumor_n = FALSE,
    tumor_m = FALSE
  )
  cindex <- current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]
  write.csv(cindex, paste0("Outputs/glmnet_cindices/cindex_", gs, "_20_max_genes_sde.csv"))
}
```


```{r MAD across gene sizes}
# gene_sizes <- seq(1, 4000, 20)
gene_sizes <- seq(1, 20, 1)
# gene_sizes <- seq(1, 15, 1)

for (gs in gene_sizes) {
  current_cox <- cox_model_fitter(
    my_seed = 1,
    my_alpha = 1,
    cox_predictors = mad_genes,
    cox_df = scl_common,
    gene_num = gs,
    save_coefs = FALSE,
    tumor_stage = FALSE,
    tumor_n = FALSE,
    tumor_m = FALSE
  )
  cindex <- current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]
  write.csv(cindex, paste0("Outputs/glmnet_cindices/cindex_", gs, "_20_max_genes.csv"))
}
```

```{r mad + sde}
mad_sde_optimized <- two_weight_optimizer(
  first.metric = mad_genes,
  second.metric = sde_genes,
  my.start = 0,
  my.finish = 1,
  step.size = 0.1,
  my.filename = paste0("Outputs/Optimization_mad_sde_1_alpha.rds")
)

for (ms in mad_sde_optimized) {
  for (gs in gene_sizes) {
    current_cox <- cox_model_fitter(
      my_seed = 1,
      my_alpha = 1,
      cox_predictors = ms,
      cox_df = scl_common,
      gene_num = gs,
      save_coefs = FALSE,
      tumor_stage = FALSE,
      tumor_n = FALSE,
      tumor_m = FALSE,
      calc_auc = FALSE,
      cat_preds = FALSE,
      n_folds = 10
    )
    cindex <- current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]
    write.csv(cindex, paste0("Outputs/glmnet_cindices/cindex_", gs, "_mad_sde_optimized.csv"))
  }
}
```


```{r mirna sde}
mirna_sde_optimized <- two_weight_optimizer(
  first.metric = mirna_genes,
  second.metric = sde_genes,
  my.start = 0,
  my.finish = 1,
  step.size = 0.1,
  my.filename = paste0("Outputs/Optimization_mirna_sde_1_alpha.rds")
)

for (ms in mirna_sde_optimized) {
  for (gs in gene_sizes) {
    current_cox <- cox_model_fitter(
      my_seed = 1,
      my_alpha = 1,
      cox_predictors = ms,
      cox_df = scl_common,
      gene_num = gs,
      save_coefs = FALSE,
      tumor_stage = FALSE,
      tumor_n = FALSE,
      tumor_m = FALSE,
      calc_auc = FALSE,
      cat_preds = FALSE,
      n_folds = 10
    )
    cindex <- current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)]
    write.csv(cindex, paste0("Outputs/glmnet_cindices/cindex_", gs, "_mirna_sde_optimized.csv"))
  }
}
```



```{r emt genes only}
emt_genes <- read.csv("Data/emt_genes_tian.txt", sep = "\t")
gene_sizes <- seq(1, 3000, 20)
cox_outputs <- list()
counter <- 1

for (gs in gene_sizes) {
  current_cox <- cox_model_fitter(
    my_seed = 1,
    my_alpha = 0.5,
    cox_predictors = emt_genes$Gene[1:gs],
    cox_df = scl_common,
    gene_num = gs,
    save_coefs = FALSE,
    tumor_stage = FALSE,
    tumor_n = FALSE,
    tumor_m = FALSE,
    calc_auc = FALSE,
    cat_preds = FALSE,
    n_folds = 10
  )
  cindices <- c(cindices, current_cox$CV$cvm[which(current_cox$CV$lambda == current_cox$CV$lambda.min)])
  num_of_active_genes <- c(num_of_active_genes, length(current_cox$`Active Genes`))
}

df <- as.data.frame(cbind(cindices, num_of_active_genes))
write.csv(df, "Outputs/emt_genes_only_cindex_performance.csv")
```
